### ISSUE TITLE
Created at/ Updated At

### ISSUE THREAD

**Issue by wil222** [GregoryVds/start_in_it_backend#1]
Petit détail : les champs Created at/ Updated At des exercices ne se mettent pas à jour correctement : les deux se mettent à la même date lors d'un update, au lieu de conserver la date de création.

**Comment by wil222** [comment]
Le problème est plus grave en fait...
J'ai modifié l'exercice d'ID 25, mais au lieu de le modifier, le ID 27 a été créé, tout en laissant le 25 dans la mémoire de la track. Il en résulte un null pointer exception lors de la lecture de la liste de track faisant crasher l'application
![capture du 2015-04-22 00 30 54](https://cloud.githubusercontent.com/assets/6359461/7264084/f14dbd7a-e887-11e4-9177-49153342dfa9.png)

**Comment by wil222** [comment]
Vous remarquerez le exercise_type : nil_class de l'id 25 qui était bien à radio_button avant
L'id 25 apparait bien dans la liste de tous les exercices, mais impossible de modifier ou supprimer : 
"The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved."

**Comment by GregoryVds** [comment]
Ok merci Wil, je regarde ça!

**Comment by GregoryVds** [comment]
C'est réglé, je déploie la version corrigée dans qq minutes.

**Comment by wil222** [comment]
C'est pas réglé... 
![capture du 2015-04-23 11 36 14](https://cloud.githubusercontent.com/assets/6359461/7294394/2dea1c12-e9ad-11e4-94eb-d334005996d7.png)

**Comment by GregoryVds** [comment]
Ce sont des nouvelles données? Ou ce sont les données corrompues d'avant? Je n'ai pas enlevé les précédentes données corrompues, je vais le faire maintenant.

**Comment by GregoryVds** [comment]
Je viens d'enlever la donnée corrompue, mais c'est réglé je pense.

**Comment by wil222** [comment]
Parfait !
L'application crashait encore à cause des données corrompues... (j'ai pas trouvé comment les retirer)

**Comment by GregoryVds** [comment]
Ok super. T'aurais pas su les enlever en fait, faut avoir accès à la db.
